### ISSUE TITLE
Runtime error: Possible Shebang Line Error

### ISSUE THREAD

**Issue by ajaygandecha** [comp426-2023-spring/a03#1]
#### What is happening?

Currently, the autograder is returning the same error on over half of the tests. The error reads:

```
/bin/sh: 1: Syntax error: "(" unexpected
```

However, when I run the module locally, it works perfectly as expected within the CLI.

#### What does the error say is happening?

The error is referring to a supposed syntax error in my files.

#### What do you think the error means?

After researching the cause of this error online, I believe that this error is not necessarily being caused by a *syntax error*, but rather with the **shebang line** that I have included at the top of my `*-cli.js` files. 

Currently, I am using the following to represent that the files should be run as a *Node* script:
```
#!/usr/bin/env node
```

Running the scripts locally using `node-rps` and `node-rpsls` commands in my command line (after running `npm link`) is working as expected. The output formats match what is expected as defined in the `README.md` file for a03.

I suspect that I am using the wrong shebang line for the autograder, or that the autograder expects a different one than what works on my computer! I am not sure which shebang line would be necessary to use here, or if I am using the right one but there is some issue elsewhere in my code. I extensively checked all of my parenthesis, and there does not seem to be any issues with that. In addition, there were no syntax errors flagged in the command line locally when attempting to test the commands.

#### Node.js version

Currently using Node version `v16.19.0`.

#### Operating system

Currently using `MacOS Ventura 13.0`.

**Comment by daqichen** [comment]
@ajaygandecha 
I agree with the `shebang` line being a possible cause:
> After researching the cause of this error online, I believe that this error is not necessarily being caused by a syntax error, but rather with the shebang line that I have included at the top of my `*-cli.js` files.

And after looking at your repo, noticed a few things:

1. The instruction includes the following:
> Put the appropriate shebang in the `./bin/*-cli.js` files.

while in your repo, your helper functions in `./lib/*.js` also had the shebang line at the start.

2. (Unrelated to the issue you raised) In your `./bin/*-cli.js`, you are using `require()` ES module and according to `README.md`:
> Importable modules for RPS and RPSLS using ES `import` method.

Hope this helps!

**Comment by ajaygandecha** [comment]
@daqichen, thank you so much for the response!

Agree about the extra shebang on the `./lib/*.js` file -- I added this is a second commit to see if that fixed anything, which it did not. I removed it again, however the same error persists.

Also regarding #2, I tried to use `import` in both of the `./bin/*-cli.js` files, however, it gives a syntax error when trying to run it locally:

```
SyntaxError: Cannot use import statement outside a module
```
Because of this, I opted to use `require()`. Is there a different setup needed in order for `import` to work in these files?

Thanks for the help!

**Comment by daqichen** [comment]
@ajaygandecha The reason you are encountering this:
> `SyntaxError: Cannot use import statement outside a module`

is because you are missing the following line in your `package.json`:
```
"type": "module"
```

**Comment by ajaygandecha** [comment]
@daqichen great, thank you! I have fixed the import statements in my `*-cli.js` files to use `import` rather than `require()`, and again, the CLI is again working as expected locally.

It is still causing the same syntax error in the autograder, so I am trying to figure out the cause of this. I did just notice an update in the autograder workflow which seemed to fix a regex error near the top, which is helpful.

**Comment by daqichen** [comment]
@ajaygandecha  Awesome, I am looking into the issue, but would just like to ask for some further clarifications:
1. Did your program pass all the tests in `autograding.json` locally?
2. If you are not sure where to find those tests, they are located at `./.github/classroom/autograding.json`, so you can try to run the tests for "Play Rock Paper Scissors with an opponent" with this commend: 
```
SHOT=("rock" "paper" "scissors"); echo ${SHOT[$RANDOM % ${#SHOT[@]} ]}; node-rps $SHOT
```

This information will be helpful for me to figure out if anything needs to happen on the autograding tests side.

**Comment by ajaygandecha** [comment]
@daqichen Thank you for showing this! I did run all of the commands, for example the one mentioned above, and these do work locally. For example, this is the following output when running the line above in console:

```
SHOT=("rock" "paper" "scissors"); echo ${SHOT[$RANDOM % ${#SHOT[@]} ]}; node-rps $SHOT
paper
{"player":"rock","opponent":"scissors","winner":"win"}
```

Now I might be wrong, but at first glance the output seems to be different than the randomly selected shot. I am not sure if this is because `paper` is `echo`ed randomly, but then the autograder passes in the first and not the randomly chosen one.

-----

Also, another question, for the `"RPSLS out of range"` test, the following is used:
```
SHOT=("Data" "leaf" "hammer" "pencil" "mouse"); echo ${SHOT[$RANDOM % ${#SHOT[@]} ]}; node-rpsls $SHOT"
```
The `.json` seems to expect output for more than one input, however, I was just curious if the autograder line actually chose multiple items from the input list. I ask because my input when running the above line treats it as a single invalid input rather than multiple.

When I locally run an example, such as `node-rpsls lizard spock`, my terminal shows the correct response, which is `"Arguments out of range."`, the help text, and then the rules text.

-----

Again, thank you so much for the help! I will say that I did not encounter that syntax errors with any of the local autograder tests.

**Comment by daqichen** [comment]
@ajaygandecha 
1. a small thing I noticed in your local output:
> ```
> {"player":"rock","opponent":"scissors","winner":"win"}
> ```
The last field name should be `"result"` instead of `"winner"`

2. And about:
> Now I might be wrong, but at first glance the output seems to be different than the randomly selected shot. I am not sure if this is because `paper` is echoed randomly, but then the autograder passes in the first and not the randomly chosen one.

I am looking into the autograder command and did verify that in the cmd `SHOT=("rock" "paper" "scissors"); echo ${SHOT[$RANDOM % ${#SHOT[@]} ]}; node-rps $SHOT`, `${SHOT[$RANDOM % ${#SHOT[@]} ]}` and `$SHOT` are outputting two different random choices. This however shouldn't impact you passing that test since the test is checking for regex matching. 

3. For
> Also, another question, for the "`RPSLS out of range`" test, the following is used: ...

You are referring to the case of having multiple inputs, but if you look at the possible inputs from the test cmd `SHOT=("Data" "leaf" "hammer" "pencil" "mouse");`, those are **invalid** cases, so make sure your program can handle those cases.

4. Back to the original issue with:
```
/bin/sh: 1: Syntax error: "(" unexpected
```
I am still looking into the issue and as part of the testing for resolving the syntax error, **I will make one update to the `autograding.json` in a few moments, please pull in those changes and push in changes I mentioned above.**

Let's see if that resolves the syntax error message.

**Comment by ajaygandecha** [comment]
@daqichen,

1. Thank you for pointing this out, fixed!
2. I think this works as expected for me locally, but I will double check.
3. Same as above
4. Thank you! Unfortunately the syntax error remains, but @jdmar3 mentioned in class today that a fix might be coming. Again, really appreciate the help!

**Comment by daqichen** [comment]
@ajaygandecha Latest fix to autograder should take care of this error! Closing this issue for now.

**Comment by ajaygandecha** [comment]
@daqichen great, everything works perfectly now!! Appreciate the help
