### ISSUE TITLE
Autograder: Possible mistake in regular expression

### ISSUE THREAD

**Issue by zhangwy324** [comp426-2023-spring/a03#2]
#### Which autograder check is failing?
Play Rock Paper Scissors without opponent

#### What is happening?
It only passes when scissors is chosen

#### Failed workflow run URL
https://github.com/comp426-2023-spring/a03-zhangwy324/actions/runs/4219711313/jobs/7325392634

#### What should be happening?
It should pass when {"player":"rock"} is the output

#### Screenshots of your local test(s)
![image](https://user-images.githubusercontent.com/97468260/220002738-d5bfffbd-4f4c-4e20-92fc-986ef16ea48c.png)

#### Why do you think the autograder is failing? 
I think the regular expression has a mistake. Inside autograding.json, the regular expression that is being check for this check is 
`{\"player\":\"([R|r]ock|[P|p]aper|[S|s]cissors\")}`
I think that the last `\"` should be outside the parenthesis instead of inside. I think this is producing the error.

**Comment by daqichen** [comment]
@zhangwy324  Thank you for noting this, just made that fix in the autograding tests, should be working as expected now! Closing this issue.
