### ISSUE TITLE
Autograder: No output for all checks that runs a shebang

### ISSUE THREAD

**Issue by zhangwy324** [comp426-2023-spring/a03#3]
#### Which autograder check is failing?
All checks including and after `Play Rock Paper Scissors with an opponent`

#### What is happening?
It seems like my code produces no output when the autograder is checking them. 

#### Failed workflow run URL
https://github.com/comp426-2023-spring/a03-zhangwy324/actions/runs/4219800935/jobs/7325504926

#### What should be happening?
My code should always produce some output when running `node-rps` followed by anything. 

#### Screenshots of your local test(s)
![image](https://user-images.githubusercontent.com/97468260/220006158-cfaafa48-215b-4331-8ba6-7c8e45572521.png)

#### Why do you think the autograder is failing? 
I am not too sure. It might be the shebang in the beginning and it is not running a valid script, because if it is, my code should always produce some output. I think it is the shebang because all autograder tests that run `#!/bin/bash;` in the beginning are not producing any output.

**Comment by daqichen** [comment]
@zhangwy324 See #1 

Latest fix to autograder should have taken care of the behavior mentioned above, closing this for now.
