### ISSUE TITLE
Runtime error: node-rps and node-rpsls commands not working when node ./rps-cli.js and node ./rpsls-cli.js are

### ISSUE THREAD

**Issue by briannata** [comp426-2023-spring/a03#4]
#### What is happening?
When I run "node ./rps-cli.js" or "node ./rpsls-cli.js", my code works like the assignment specifies, but when I try to run node-rps and node-rpsls, I get errors. I linked it and ran the chmod command specified in the assignment and I'm not sure where I'm going wrong.

#### What does the error say is happening?
The error says that it cannot find the command, file, or directory when I run "node-rps" or "node-rpsls".

#### What do you think the error means?
I think this error means that the bin commands in my package.json file are not working correctly. Maybe I missed a step or command?

#### Command string
Not working: "node-rps" and "node-rpsls"
Working: "node ./rps-cli.js" and "node ./rpsls-cli.js"

#### Screenshots
![image](https://user-images.githubusercontent.com/37271052/220010329-c3c4f44c-35ad-4a21-9c95-bdeffbc3f284.png)
![image](https://user-images.githubusercontent.com/37271052/220010428-7bac315f-4a8a-4b28-982d-2890b59f9868.png)

#### Error log
node-rpsls: command not found
/usr/bin/env: ‘node\r’: No such file or directory

#### Node.js version
v18.13.0

#### Operating system
Windows 10

**Comment by daqichen** [comment]
@briannata If you see the output to your autograding test results, you will see that there is a valid output to `Play Rock Paper Scissors without opponent` which runs `node-rps`, however no valid output for test `Play Rock Paper Scissors Lizard Spock without an opponent` which runs `node-rpsls`. 

In your `package.json`, you have:
```
"bin": {
    "node-rps": "./bin/rps-cli.js",
    "node-rpsls": "rpsls-cli.js"
  },
```

You should be able to proceed from here, closing the issue for now.
