### ISSUE TITLE
Autograder: Typo in autograding.json

### ISSUE THREAD

**Issue by zhangwy324** [comp426-2023-spring/a03#5]
#### Which autograder check is failing?
RPSLS Rules

#### What is happening?
Running the `node-rps` instead of `node-rpsls`

#### Failed workflow run URL
https://github.com/comp426-2023-spring/a03-zhangwy324/actions/runs/4220844619/jobs/7327502857

#### What should be happening?
The autograder should run `node-rpsls`

#### Why do you think the autograder is failing? 
Line 95 of autograding.json should run `node-rpsls`
Thank you Jen for working so late on the autograder! I really appreciate it!

**Comment by daqichen** [comment]
@zhangwy324  Thank you for pointing that out, it is now fixed. 
And not a problem, closing this issue.
