### ISSUE TITLE
Autograder: Test Are Failing That Should Be Passing

### ISSUE THREAD

**Issue by aayush110** [comp426-2023-spring/a03#7]
So I went to office hours and the TA said there could be an autograder bug because my code is failing the following tests. The TA was more than certain about the correctness of the code written, and strongly feel there is an autograder bug because they stated that even their code template is failing the following tests.

These are the tests that are failing:

Play Rock Paper Scissors without opponent
Play Rock Paper Scissors Lizard Spock without an opponent
Play Rock Paper Scissors with an opponent
Play Rock Paper Scissors Lizard Spock with an opponent

**Comment by daqichen** [comment]
@aayush110 If you read the [logs](https://github.com/comp426-2023-spring/a03-aayush110/actions/runs/4324955173/jobs/7550465070#step:3:43), you can see where your output differs from the expected results:

For example, for `Play Rock Paper Scissors without opponent`
```
Expected:{"player":"([R|r]ock|[P|p]aper|[S|s]cissors)"}

Actual:{"personplaying":"scissors"}
```
This is not an issue with the autograder.
