### ISSUE TITLE
Runtime error: rsp and rpsls not importable

### ISSUE THREAD

**Issue by azaria-p** [comp426-2023-spring/a03#8]
#### What is happening?
Getting an autograder error because modules cannot be imported.

#### What does the error say is happening?
<img width="445" alt="image" src="https://user-images.githubusercontent.com/84456426/228045625-a88d4967-a3b1-4081-b509-751b2940550f.png">

#### What do you think the error means?
rps and rspls cannot be accessed outside of the package/ they are not in the correct form

#### Node.js version
18.13.0

#### Operating system
Linux UNC-R90YENDW 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by daqichen** [comment]
@azaria-p 

You have [this](https://github.com/comp426-2023-spring/a03-azaria-p/blob/main/package.json#L10), which nested the `type` field incorrectly. 

See [documentation](https://nodejs.org/api/packages.html#type)

```
// package.json
{
  "type": "module"
}

```

**Comment by azaria-p** [comment]
Originally that was git, and I had the same issue. I looked online and it said that changing the type to module might fix it, hence why that's like that. So I still have the issue.

**Comment by daqichen** [comment]
@azaria-p The documentation states to have `type` in the outermost level of your `package.json`. Meanwhile, yours is nested. Please check your code: https://github.com/comp426-2023-spring/a03-azaria-p/blob/main/package.json#L10
